from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from .views import (
    register,
    login_view,
    attendance_view,
    user_list_view,
    user_detail_view,
    department_list_view,
    department_detail_view,
    section_list_view,
    section_detail_view,
    subject_list_view,
    subject_detail_view,
    bulk_student_upload_view,
    bulk_faculty_upload_view,
    bulk_subject_upload_view,
    export_attendance_excel_view,
    export_attendance_date_wise_excel_view,
    attendance_portal_freeze_view,
    bulk_attendance_upload_view,
    sample_student_registration_excel_view,
    sample_faculty_registration_excel_view,
    sample_subjects_excel_view,
    sample_bulk_attendance_excel_view,
    faculty_department_sections_view,
    qr_attendance_sessions_view,
    qr_attendance_session_detail_view,
    qr_attendance_mark_view,
    qr_attendance_records_view,
    mentor_assignment_view,
    mentor_assignment_detail_view,
    mentor_students_view,
    bulk_mentor_assignment_view,
    student_academic_records_view,
    student_academic_record_detail_view,
    mentor_attendance_records_view,
    mentor_attendance_record_detail_view,
    counselling_notes_view,
    counselling_note_detail_view,
    students_list_view,
    student_behaviour_records_view,
    student_behaviour_record_detail_view,
    student_career_records_view,
    student_career_record_detail_view,
    student_link_records_view,
    student_link_record_detail_view,
    student_training_records_view,
    student_training_record_detail_view,
)

urlpatterns = [
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('register/', register),
    path('login/', login_view),
    path('attendance/', attendance_view),
    path('attendance-portal-freeze/', attendance_portal_freeze_view),
    path('users/', user_list_view),
    path('users/<int:pk>/', user_detail_view),
    path('students/', students_list_view),
    path('students/', students_list_view),
    path('departments/', department_list_view),
    path('departments/<int:pk>/', department_detail_view),
    path('sections/', section_list_view),
    path('sections/<int:pk>/', section_detail_view),
    path('subjects/', subject_list_view),
    path('subjects/<int:pk>/', subject_detail_view),
    path('students/bulk-upload/', bulk_student_upload_view),
    path('faculty/bulk-upload/', bulk_faculty_upload_view),
    path('subjects/bulk-upload/', bulk_subject_upload_view),
    path('export/attendance-data/', export_attendance_excel_view),
    path('export/attendance-date-wise/', export_attendance_date_wise_excel_view),
    path('attendance/bulk-upload/', bulk_attendance_upload_view),
    path('samples/student-registration/', sample_student_registration_excel_view),
    path('samples/faculty-registration/', sample_faculty_registration_excel_view),
    path('samples/subjects/', sample_subjects_excel_view),
    path('samples/bulk-attendance/', sample_bulk_attendance_excel_view),
    path('faculty-department-sections/<int:user_id>/', faculty_department_sections_view),
    path('qr-attendance/sessions/', qr_attendance_sessions_view),
    path('qr-attendance/sessions/<int:session_id>/', qr_attendance_session_detail_view),
    path('qr-attendance/mark/', qr_attendance_mark_view),
    path('qr-attendance/sessions/<int:session_id>/records/', qr_attendance_records_view),
    path('mentor-assignments/', mentor_assignment_view),
    path('mentor-assignments/<int:assignment_id>/', mentor_assignment_detail_view),
    path('mentor-assignments/bulk/', bulk_mentor_assignment_view),
    path('mentor-students/', mentor_students_view),
    path('mentor-students/<int:mentor_id>/', mentor_students_view),
    path('students/<int:student_id>/academic-records/', student_academic_records_view),
    path('students/<int:student_id>/academic-records/<int:record_id>/', student_academic_record_detail_view),
    path('students/<int:student_id>/mentor-attendance/', mentor_attendance_records_view),
    path('students/<int:student_id>/mentor-attendance/<int:record_id>/', mentor_attendance_record_detail_view),
    path('students/<int:student_id>/counselling-notes/', counselling_notes_view),
    path('students/<int:student_id>/counselling-notes/<int:note_id>/', counselling_note_detail_view),
    path('students/<int:student_id>/behaviour-records/', student_behaviour_records_view),
    path('students/<int:student_id>/behaviour-records/<int:record_id>/', student_behaviour_record_detail_view),
    path('students/<int:student_id>/career-records/', student_career_records_view),
    path('students/<int:student_id>/career-records/<int:record_id>/', student_career_record_detail_view),
    path('students/<int:student_id>/link-records/', student_link_records_view),
    path('students/<int:student_id>/link-records/<int:record_id>/', student_link_record_detail_view),
    path('students/<int:student_id>/training-records/', student_training_records_view),
    path('students/<int:student_id>/training-records/<int:record_id>/', student_training_record_detail_view),
]
