# Generated by Django 6.0.3 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_qrattendancesession_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrattendancesession',
            name='custom_session_id',
            field=models.CharField(blank=True, default='', help_text='Rotating 5-digit session ID for security', max_length=5),
        ),
        migrations.AddField(
            model_name='qrattendancesession',
            name='session_id_expires_at',
            field=models.DateTimeField(blank=True, help_text='When the custom session ID expires', null=True),
        ),
    ]
