# Generated by Django 6.0.3 on 2026-09-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_qrattendancesession_custom_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrattendancesession',
            name='branches',
            field=models.CharField(blank=True, default='', help_text='Comma-separated branch codes', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('admin', 'Admin'), ('mentor', 'Mentor')], max_length=20),
        ),
    ]
