# Generated by Django 6.0.3 on 2026-09-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_user_address_user_admission_category_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.TextField(blank=True, help_text='Achievements and awards', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='areas_of_interest',
            field=models.TextField(blank=True, help_text='Areas of interest', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hobbies',
            field=models.TextField(blank=True, help_text='Hobbies and interests', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='intermediate_board',
            field=models.CharField(blank=True, help_text='Intermediate/Diploma Board', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='intermediate_class',
            field=models.CharField(blank=True, help_text='Class/Distinction', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='intermediate_college',
            field=models.CharField(blank=True, help_text='College Name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='intermediate_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage/CGPA', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='local',
            field=models.CharField(blank=True, help_text='Local language', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='medium_of_instruction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mother_tongue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='other_information',
            field=models.TextField(blank=True, help_text='Any other information', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ssc_board',
            field=models.CharField(blank=True, help_text='SSC/CBSE/ICSE Board', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ssc_class',
            field=models.CharField(blank=True, help_text='Class/Distinction', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ssc_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage/CGPA', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ssc_school',
            field=models.CharField(blank=True, help_text='School Name', max_length=200, null=True),
        ),
    ]
