# Generated by Django 6.0.3 on 2026-09-07 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_user_achievements_user_areas_of_interest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(help_text='Course or subject name', max_length=200)),
                ('semester', models.CharField(help_text='Semester (e.g., 1, 2, 3, 4)', max_length=20)),
                ('academic_year', models.CharField(help_text='Academic year (e.g., 2023-24)', max_length=20)),
                ('mid1_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Mid-1 marks', max_digits=5, null=True)),
                ('mid2_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Mid-2 marks', max_digits=5, null=True)),
                ('cie_marks', models.DecimalField(blank=True, decimal_places=2, help_text='CIE/Internal marks', max_digits=5, null=True)),
                ('total_internal_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Total internal marks', max_digits=5, null=True)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Marks obtained', max_digits=5, null=True)),
                ('credits_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Credits obtained', max_digits=5, null=True)),
                ('sgpa', models.DecimalField(blank=True, decimal_places=2, help_text='SGPA for the semester', max_digits=3, null=True)),
                ('audit_course_cleared', models.BooleanField(default=False, help_text='Whether audit course is cleared')),
                ('grade', models.CharField(blank=True, help_text='Grade obtained', max_length=10, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_academic_records', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Academic Record',
                'verbose_name_plural': 'Academic Records',
                'ordering': ['-academic_year', 'semester', 'course_name'],
            },
        ),
    ]
