# Generated by Django 6.0.3 on 2026-09-07 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_academicrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(help_text='Name of the course/subject', max_length=200)),
                ('semester', models.CharField(help_text='Semester (e.g., 1-1, 1-2, 2-1, 2-2)', max_length=50)),
                ('academic_year', models.CharField(help_text='Academic year (e.g., 2023-24)', max_length=20)),
                ('mid1_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Mid-1 marks', max_digits=5, null=True)),
                ('mid2_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Mid-2 marks', max_digits=5, null=True)),
                ('cie_marks', models.DecimalField(blank=True, decimal_places=2, help_text='CIE/Internal marks', max_digits=5, null=True)),
                ('total_internal_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Total internal marks', max_digits=5, null=True)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Marks obtained', max_digits=5, null=True)),
                ('credits_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Credits obtained', max_digits=5, null=True)),
                ('sgpa', models.DecimalField(blank=True, decimal_places=2, help_text='SGPA for the semester', max_digits=5, null=True)),
                ('audit_course_cleared', models.BooleanField(default=False, help_text='Whether audit course is cleared')),
                ('grade', models.CharField(blank=True, help_text='Grade obtained (O, A+, A, B+, B, C, etc.)', max_length=10, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks about the academic performance', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Mentor who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_academic_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Academic Record',
                'verbose_name_plural': 'Student Academic Records',
                'ordering': ['-academic_year', 'semester', 'course_name'],
            },
        ),
        migrations.DeleteModel(
            name='AcademicRecord',
        ),
    ]
