# Generated by Django 6.0.3 on 2026-09-07 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_studentacademicrecord_delete_academicrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='Month (e.g., January, February)', max_length=20)),
                ('semester', models.CharField(help_text='Semester (e.g., 1-1, 1-2, 2-1, 2-2)', max_length=50)),
                ('academic_year', models.CharField(help_text='Academic year (e.g., 2023-24)', max_length=20)),
                ('total_classes', models.IntegerField(default=0, help_text='Total number of classes conducted')),
                ('classes_attended', models.IntegerField(default=0, help_text='Number of classes attended by student')),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Attendance percentage', max_digits=5)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks about attendance', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entered_attendance_records', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentor Attendance Record',
                'verbose_name_plural': 'Mentor Attendance Records',
                'ordering': ['-academic_year', 'semester', 'month'],
                'unique_together': {('student', 'month', 'semester', 'academic_year')},
            },
        ),
    ]
