# Generated by Django 5.0.4 on 2026-09-07 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_mentorattendancerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(choices=[('extra_curricular', 'Extra-Curricular'), ('co_curricular', 'Co-Curricular'), ('representation', 'Representation'), ('participation', 'Participation')], help_text='Type of achievement', max_length=50)),
                ('activity_name', models.CharField(help_text='Name of the activity/event', max_length=200)),
                ('event_name', models.CharField(help_text='Specific event name', max_length=200)),
                ('participation_level', models.CharField(help_text='Level of participation (e.g., College, District, State, National)', max_length=100)),
                ('achievement_details', models.TextField(help_text='Details about the achievement')),
                ('date_achieved', models.DateField(help_text='Date when the achievement was made')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Achievement',
                'verbose_name_plural': 'Student Achievements',
                'ordering': ['-date_achieved', '-created_at'],
            },
        ),
    ]
