# Generated by Django 5.0.4 on 2026-09-07 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_studentachievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark_date', models.DateField(help_text='Date of the remark')),
                ('mentoring_area', models.CharField(choices=[('academic', 'Academic'), ('attendance', 'Attendance'), ('discipline', 'Discipline'), ('other', 'Other')], help_text='Area of mentoring', max_length=50)),
                ('remarks', models.TextField(help_text='Mentor remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_remarks', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_remarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mentor Remark',
                'verbose_name_plural': 'Mentor Remarks',
                'ordering': ['-remark_date', '-created_at'],
            },
        ),
    ]
