# Generated by Django 5.0.4 on 2026-09-07 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_mentorremark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorremark',
            name='attendance_month',
            field=models.CharField(blank=True, help_text='Month for attendance data', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mentorremark',
            name='attendance_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Attendance percentage for the period', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mentorremark',
            name='attendance_semester',
            field=models.CharField(blank=True, help_text='Semester for attendance data', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='mentorremark',
            name='attendance_year',
            field=models.CharField(blank=True, help_text='Academic year for attendance data', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mentorremark',
            name='classes_attended',
            field=models.IntegerField(blank=True, help_text='Classes attended in the period', null=True),
        ),
        migrations.AddField(
            model_name='mentorremark',
            name='total_classes',
            field=models.IntegerField(blank=True, help_text='Total classes in the period', null=True),
        ),
    ]
