# Generated by Django 5.0.4 on 2026-09-07 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_mentorremark_attendance_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorremark',
            name='attendance_month',
        ),
        migrations.RemoveField(
            model_name='mentorremark',
            name='attendance_percentage',
        ),
        migrations.RemoveField(
            model_name='mentorremark',
            name='attendance_semester',
        ),
        migrations.RemoveField(
            model_name='mentorremark',
            name='attendance_year',
        ),
        migrations.RemoveField(
            model_name='mentorremark',
            name='classes_attended',
        ),
        migrations.RemoveField(
            model_name='mentorremark',
            name='total_classes',
        ),
    ]
