# Generated by Django 5.0.4 on 2026-09-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_mentorremark_attendance_month_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guardian_mobile',
            field=models.CharField(blank=True, help_text='Guardian mobile number', max_length=20, null=True),
        ),
    ]
