# Generated by Django 5.0.4 on 2026-09-08 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_user_guardian_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounsellingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counselling_date', models.DateField(help_text='Date of the counselling session')),
                ('remarks', models.TextField(help_text='Counselling remarks and notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_counselling_notes', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselling_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Counselling Note',
                'verbose_name_plural': 'Counselling Notes',
                'ordering': ['-counselling_date', '-created_at'],
            },
        ),
    ]
