# Generated by Django 6.0.3 on 2026-09-09 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_counsellingnote'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBehaviour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behaviour_category', models.CharField(choices=[('discipline', 'Discipline'), ('participation', 'Class Participation'), ('teamwork', 'Teamwork'), ('leadership', 'Leadership'), ('communication', 'Communication'), ('time_management', 'Time Management'), ('other', 'Other')], help_text='Category of behaviour', max_length=50)),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Below Average'), (3, 'Average'), (4, 'Good'), (5, 'Excellent')], help_text='Rating (1-5)')),
                ('assessment_date', models.DateField(help_text='Date of assessment')),
                ('positive_aspects', models.TextField(blank=True, help_text='Positive aspects observed', null=True)),
                ('areas_for_improvement', models.TextField(blank=True, help_text='Areas needing improvement', null=True)),
                ('action_plan', models.TextField(blank=True, help_text='Action plan for improvement', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks about behaviour', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_behaviours', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behaviour_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Behaviour',
                'verbose_name_plural': 'Student Behaviours',
                'ordering': ['-assessment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentCareer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, help_text='Company name if placed', max_length=200, null=True)),
                ('job_role', models.CharField(blank=True, help_text='Job role/designation', max_length=200, null=True)),
                ('career_status', models.CharField(choices=[('placed', 'Placed'), ('seeking', 'Seeking Opportunities'), ('higher_studies', 'Pursuing Higher Studies'), ('entrepreneur', 'Entrepreneur'), ('not_placed', 'Not Placed')], help_text='Current career status', max_length=50)),
                ('placement_date', models.DateField(blank=True, help_text='Date of placement', null=True)),
                ('salary_package', models.CharField(blank=True, help_text='Salary package (e.g., 6 LPA)', max_length=100, null=True)),
                ('skills_for_career', models.TextField(blank=True, help_text='Skills relevant for career', null=True)),
                ('career_goals', models.TextField(blank=True, help_text='Student career goals', null=True)),
                ('guidance_provided', models.TextField(blank=True, help_text='Career guidance provided by mentor', null=True)),
                ('resume_status', models.CharField(blank=True, help_text='Resume preparation status', max_length=50, null=True)),
                ('interview_preparation', models.TextField(blank=True, help_text='Interview preparation notes', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks about career', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_careers', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Career',
                'verbose_name_plural': 'Student Careers',
                'ordering': ['-placement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_title', models.CharField(help_text='Title of the link/resource', max_length=200)),
                ('link_url', models.URLField(help_text='URL of the resource')),
                ('link_category', models.CharField(choices=[('academic', 'Academic Resources'), ('career', 'Career Resources'), ('skill_development', 'Skill Development'), ('certification', 'Certification Resources'), ('placement', 'Placement Resources'), ('other', 'Other')], help_text='Category of the link', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of the resource', null=True)),
                ('importance', models.CharField(blank=True, help_text='Importance level (e.g., High, Medium, Low)', max_length=50, null=True)),
                ('status', models.CharField(default='pending', help_text='Status (e.g., pending, completed, in_progress)', max_length=50)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks about the link', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_links', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Link',
                'verbose_name_plural': 'Student Links',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(help_text='Name of the training program', max_length=200)),
                ('training_type', models.CharField(choices=[('technical', 'Technical Training'), ('soft_skills', 'Soft Skills Training'), ('industry', 'Industry Training'), ('certification', 'Certification Program'), ('workshop', 'Workshop'), ('other', 'Other')], help_text='Type of training', max_length=50)),
                ('organization', models.CharField(blank=True, help_text='Organization providing training', max_length=200, null=True)),
                ('start_date', models.DateField(help_text='Start date of training')),
                ('end_date', models.DateField(help_text='End date of training')),
                ('duration_hours', models.IntegerField(blank=True, help_text='Duration in hours', null=True)),
                ('skills_learned', models.TextField(blank=True, help_text='Skills learned during training', null=True)),
                ('certification_obtained', models.BooleanField(default=False, help_text='Whether certification was obtained')),
                ('certificate_name', models.CharField(blank=True, help_text='Name of certificate obtained', max_length=200, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks about the training', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_trainings', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Training',
                'verbose_name_plural': 'Student Trainings',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
    ]
