# Generated by Django 5.0.4 on 2026-09-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_studentbehaviour_studentcareer_studentlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellingnote',
            name='category',
            field=models.CharField(choices=[('training', 'Training'), ('career', 'Career'), ('behaviour', 'Behaviour'), ('student_links', 'Student Links')], default='training', help_text='Category of counselling', max_length=50),
        ),
    ]
