# Generated by Django 5.0.4 on 2026-09-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_counsellingnote_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellingnote',
            name='category',
            field=models.CharField(blank=True, choices=[('training', 'Training'), ('career', 'Career'), ('behaviour', 'Behaviour'), ('student_links', 'Student Links')], help_text='Category of counselling', max_length=50, null=True),
        ),
    ]
