# Generated by Django 5.0.4 on 2026-09-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_counsellingnote_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellingnote',
            name='remarks_status',
            field=models.CharField(blank=True, choices=[('na', 'NA'), ('yet_to_start', 'Yet to Start'), ('in_progress', 'In Progress'), ('need_help', 'Need Help'), ('comfortable', 'Comfortable')], help_text='Remarks status', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='counsellingnote',
            name='training',
            field=models.CharField(blank=True, choices=[('pps', 'PPS'), ('oop', 'OOP'), ('dbms', 'DBMS'), ('ds', 'DS'), ('daa', 'DAA'), ('console_apps', 'Console Apps'), ('backend_framework', 'Backend Framework/API'), ('frontend', 'Frontend'), ('iot_hardware', 'IOT Hardware'), ('data_analytics', 'Data Analytics'), ('certification', 'Certification'), ('hackathon', 'Hackathon'), ('internship', 'Internship')], help_text='Training type', max_length=100, null=True),
        ),
    ]
