# Generated by Django 5.0.4 on 2026-09-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_counsellingnote_remarks_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcareer',
            name='career_goal',
            field=models.CharField(blank=True, help_text='What do you want to become?', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentcareer',
            name='desired_role',
            field=models.CharField(blank=True, help_text='Which role do you want to do?', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentcareer',
            name='dream_company',
            field=models.CharField(blank=True, help_text='Dream company to work?', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentcareer',
            name='expected_package',
            field=models.CharField(blank=True, choices=[('3-6', '3-6 LPA'), ('6-10', '6-10 LPA'), ('10-15', '10-15 LPA'), ('15-20', '15-20 LPA'), ('20-25', '20-25 LPA'), ('25+', '25+ LPA')], help_text='Expected salary package', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentcareer',
            name='faculty_suggestions',
            field=models.TextField(blank=True, help_text='Suggestions from faculty', null=True),
        ),
        migrations.AddField(
            model_name='studentcareer',
            name='help_needed',
            field=models.TextField(blank=True, help_text='Need any help?', null=True),
        ),
    ]
