# Generated by Django 5.0.4 on 2026-09-10 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_studentcareer_career_goal_studentcareer_desired_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Permission name (e.g., attendance.view)', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable permission name', max_length=150)),
                ('description', models.TextField(blank=True, help_text='Description of what this permission allows')),
                ('permission_type', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], help_text='Type of permission', max_length=20)),
                ('module', models.CharField(help_text='Module this permission belongs to (e.g., attendance, students, mentorship)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['module', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('admin', 'Admin'), ('mentor', 'Mentor'), ('hod', 'HOD')], max_length=20),
        ),
        migrations.CreateModel(
            name='TabAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Role name', max_length=20)),
                ('tab', models.CharField(choices=[('dashboard', 'Dashboard'), ('attendance', 'Attendance'), ('students', 'Students'), ('mentorship', 'Mentorship'), ('reports', 'Reports'), ('settings', 'Settings'), ('faculty_portal', 'Faculty Portal'), ('student_portal', 'Student Portal'), ('mentor_dashboard', 'Mentor Dashboard'), ('admin_panel', 'Admin Panel')], help_text='Tab/section name', max_length=50)),
                ('can_access', models.BooleanField(default=True, help_text='Whether this role can access this tab')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tab Access',
                'verbose_name_plural': 'Tab Access',
                'ordering': ['role', 'tab'],
                'unique_together': {('role', 'tab')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Role name (student, faculty, admin, mentor, hod)', max_length=20)),
                ('can_access', models.BooleanField(default=True, help_text='Whether this role has this permission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='core.permission')),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'ordering': ['role', 'permission__module', 'permission__name'],
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_access', models.BooleanField(default=True, help_text='Whether this user has this permission')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='core.permission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Permission',
                'verbose_name_plural': 'User Permissions',
                'ordering': ['user__username', 'permission__module', 'permission__name'],
                'unique_together': {('user', 'permission')},
            },
        ),
    ]
