# Generated by Django 5.0.4 on 2026-09-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_permission_alter_user_role_tabaccess_rolepermission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabaccess',
            name='tab',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('students', 'Students'), ('student-detention', 'Active / Detained'), ('branches', 'Branches'), ('subjects', 'Subjects'), ('sections', 'Sections'), ('faculty', 'Manage Faculty'), ('mentors', 'Manage Mentors'), ('mentor-assignments', 'Mentor Assignments'), ('qr-attendance', 'QR Attendance'), ('mark-attendance', 'Mark Attendance'), ('attendance-records', 'Attendance Records'), ('reports', 'Data Management'), ('defaulters', 'Defaulters'), ('permissions', 'Permissions'), ('faculty-dashboard', 'Faculty Dashboard'), ('faculty-attendance', 'Mark Attendance'), ('faculty-qr-attendance', 'QR Attendance'), ('student-attendance', 'Student Attendance'), ('faculty-reports', 'My Reports'), ('faculty-subjects', 'My Subjects'), ('mentor-dashboard', 'Mentor Dashboard'), ('mentor-students', 'My Students'), ('all-students', 'View Complete Profile'), ('academic-records', 'Academic Profile'), ('mentor-attendance', 'Attendance'), ('counselling-notes', 'Counselling Notes'), ('student-dashboard', 'Student Dashboard'), ('student-attendance', 'My Attendance'), ('student-mentor-attendance', 'Mentor Attendance'), ('student-qr-attendance', 'QR Attendance'), ('student-subjects', 'Subjects'), ('student-details', 'Student Details'), ('educational-profile', 'Educational Profile'), ('achievements', 'Records'), ('profile', 'Profile'), ('settings', 'Settings')], help_text='Tab/section name', max_length=50),
        ),
    ]
