# Generated by Django 6.0.3 on 2026-09-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_tabaccess_tab'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentachievement',
            name='certificate',
            field=models.FileField(blank=True, help_text='Certificate file for certifications', null=True, upload_to='achievement_certificates/'),
        ),
        migrations.AlterField(
            model_name='studentachievement',
            name='achievement_type',
            field=models.CharField(choices=[('extra_curricular', 'Extra-Curricular'), ('co_curricular', 'Co-Curricular'), ('representation', 'Representation'), ('participation', 'Participation'), ('certifications', 'Certifications')], help_text='Type of achievement', max_length=50),
        ),
        migrations.AlterField(
            model_name='tabaccess',
            name='tab',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('attendance', 'Attendance'), ('students', 'Students'), ('mentorship', 'Mentorship'), ('reports', 'Reports'), ('settings', 'Settings'), ('faculty_portal', 'Faculty Portal'), ('student_portal', 'Student Portal'), ('mentor_dashboard', 'Mentor Dashboard'), ('admin_panel', 'Admin Panel')], help_text='Tab/section name', max_length=50),
        ),
    ]
