# Generated by Django 6.0.3 on 2026-09-11 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_studentachievement_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guardian_mobiles',
            field=models.JSONField(blank=True, default=list, help_text='List of guardian mobile numbers', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='guardian_mobile',
            field=models.CharField(blank=True, help_text='Guardian mobile number (legacy field)', max_length=20, null=True),
        ),
    ]
