# Generated by Django 6.0.3 on 2026-09-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_user_guardian_mobiles_alter_user_guardian_mobile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentorattendancerecord',
            options={'ordering': ['-to_date', '-from_date', 'semester'], 'verbose_name': 'Mentor Attendance Record', 'verbose_name_plural': 'Mentor Attendance Records'},
        ),
        migrations.AlterUniqueTogether(
            name='mentorattendancerecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='mentorattendancerecord',
            name='from_date',
            field=models.DateField(blank=True, help_text='From date for attendance calculation', null=True),
        ),
        migrations.AddField(
            model_name='mentorattendancerecord',
            name='to_date',
            field=models.DateField(blank=True, help_text='To date for attendance calculation', null=True),
        ),
        migrations.AlterField(
            model_name='mentorattendancerecord',
            name='academic_year',
            field=models.CharField(blank=True, help_text='Academic year (e.g., 2023-24)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mentorattendancerecord',
            name='month',
            field=models.CharField(blank=True, help_text='Month (e.g., January, February)', max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='mentorattendancerecord',
            constraint=models.UniqueConstraint(condition=models.Q(('from_date__isnull', False), ('to_date__isnull', False)), fields=('student', 'semester', 'from_date', 'to_date'), name='unique_mentor_attendance_date_range'),
        ),
    ]
